language: objective-c
podfile:  EPStackExample/podfile
before_install:
  - gem update cocoapods

script:
  - pod install --project-directory=EPStackExample
  - xctool -workspace EPStackExample/EPStackExample.xcworkspace -scheme EPStackExample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace EPStackExample/EPStackExample.xcworkspace -scheme EPStackExampleTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  
