language: objective-c
before_install:
  - gem update cocoapods

 script:
  - pod install
  - xctool -workspace EPStackExample/EPStackExample.xcworkspace -scheme EPStackExample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace EPStackExample/EPStackExample.xcworkspace -scheme EPStackExampleTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  